<?php


return [
    'routes'=> [
        [
            'name' => 'dashboard',
            'controller' => \App\Http\Controllers\Panel\DashboardController::class,
            'except' => ['show', 'destroy'],
            'permission' => 'manage-dashboard',
            'permission_name' => 'مدیریت کاربران',
            'hasDefaultRoute' => true,
            'title' => 'داشبورد',
            'icon' => 'material-icons',
            'li_text'=>'people', // from: https://material.io/icons
            'parent-menu' => '',
            'order' => 1
        ],
        [
            'name' => 'users',
            'controller' => \App\Http\Controllers\Panel\UserController::class,
            'except' => ['show', 'destroy'],
            'permission' => 'manage-users',
            'permission_name' => 'مدیریت کاربران',
            'hasDefaultRoute' => true,
            'title' => 'کاربران',
            'icon' => 'material-icons',
            'li_text'=>'people', // from: https://material.io/icons
            'parent-menu' => 'کاربران',
            'order' => 1
        ],
        [
            'name' => 'roles',
            'controller' => \App\Http\Controllers\Panel\RoleController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-roles',
            'permission_name' => 'مدیریت دسترسی به کاربران',
            'hasDefaultRoute' => true,
            'title' => 'نقش های کاربری',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'کاربران',
            'order' => 2
        ],
        [
            'name' => 'groups',
            'controller' => \App\Http\Controllers\Panel\GroupController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-groups',
            'permission_name' => 'مدیریت گروه های کاربری',
            'hasDefaultRoute' => true,
            'title' => 'گروه های کاربری',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'کاربران',
            'order' => 2
        ],
        [
            'name' => 'banks',
            'controller' => \App\Http\Controllers\Panel\BankController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-banks',
            'permission_name' => 'مدیریت بانک ها',
            'hasDefaultRoute' => true,
            'title' => 'بانک ها',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'تعاریف پایه',
            'order' => 2
        ],
        [
            'name' => 'currencies',
            'controller' => \App\Http\Controllers\Panel\CurrencyController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-currencies',
            'permission_name' => 'مدیریت ارز ها',
            'hasDefaultRoute' => true,
            'title' => 'ارز ها',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'تعاریف پایه',
            'order' => 2
        ],
        [
            'name' => 'containers',
            'controller' => \App\Http\Controllers\Panel\ContainerController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-containers',
            'permission_name' => 'مدیریت کانتینر ها',
            'hasDefaultRoute' => true,
            'title' => 'کانتینر ها',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'تعاریف پایه',
            'order' => 2
        ],
        [
            'name' => 'spirals',
            'controller' => \App\Http\Controllers\Panel\SpiralController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-spirals',
            'permission_name' => 'مدیریت مارپیچ ها',
            'hasDefaultRoute' => true,
            'title' => 'مارپیچ ها',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'تعاریف پایه',
            'order' => 2
        ],
        [
            'name' => 'sellers',
            'controller' => \App\Http\Controllers\Panel\SellerController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-sellers',
            'permission_name' => 'مدیریت فروشنده ها',
            'hasDefaultRoute' => true,
            'title' => 'فروشنده ها',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'تعاریف پایه',
            'order' => 2
        ],
        [
            'name' => 'system_controls',
            'controller' => \App\Http\Controllers\Panel\SystemControlController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-system-controls',
            'permission_name' => 'مدیریت کنترل ها',
            'hasDefaultRoute' => true,
            'title' => 'کنترل ها',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'تعاریف پایه',
            'order' => 2
        ],
        [
            'name' => 'machine_models',
            'controller' => \App\Http\Controllers\Panel\MachineModelControlController::class,
            'except' => ['show','destroy'],
            'permission' => 'manage-machine-models',
            'permission_name' => 'مدیریت مدل های دستگاه',
            'hasDefaultRoute' => true,
            'title' => 'مدل های دستگاه',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => 'تعاریف پایه',
            'order' => 2
        ],
        [
            'name' => 'orders',
            'controller' => \App\Http\Controllers\Panel\OrderController::class,
            'except' => ['destroy'],
            'permission' => 'manage-orders',
            'permission_name' => 'مدیریت سفارشات',
            'hasDefaultRoute' => true,
            'title' => 'سفارشات',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => '',
            'order' => 2
        ],
        [
            'name' => 'import_files',
            'controller' => \App\Http\Controllers\Panel\ImportFileController::class,
            'except' => ['destroy'],
            'permission' => 'manage-import-files',
            'permission_name' => 'مدیریت پرونده واردات',
            'hasDefaultRoute' => true,
            'title' => 'پرونده واردات',
            'icon' => 'material-icons',
            'li_text'=>'lock',
            'parent-menu' => '',
            'order' => 2
        ],
    ],
];
